### ISSUE TITLE
Doesn't work on Chrome 49?

### ISSUE THREAD

**Issue by hsuttong** [sitepoint-editors/The-Dawn-of-WebRTC#1]
-Cool example code. I got this to work in Firefox, but it doesn't seem to work in chrome  49.0.2623.75.

-The online demo also doesn't work but that seems to have a http/https issue:
https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

**Comment by lbarr** [comment]
@hsuttong Great catch! After Chrome 47, it is required to use a Secure SSL connection to access your camera and microphone. I have updated this demo domain to be a secure domain.
